### ISSUE TITLE
streaming skeleton occasionally crashloopbackoffs

### ISSUE THREAD

**Issue by mattmoor** [mattmoor/korpc#7]
Use the sample @ with-unary with the client running in a watch.

There's intermittently an error sending on a closed `errCh`.

**Comment by mattmoor** [comment]
```
$ kubectl logs stream-sampleservice-99xx9-deployment-579669958d-lrgxm user-container
panic: send on closed channel

goroutine 55 [running]:
main.(*server).Stream.func1(0xc0002802a0, 0x993200, 0xc0002682b0, 0xc000280360)
        /usr/local/google/home/mattmoor/go/src/github.com/mattmoor/korpc-sample/gen/entrypoint/sampleservice/stream/main.go:39 +0xe2
created by main.(*server).Stream
        /usr/local/google/home/mattmoor/go/src/github.com/mattmoor/korpc-sample/gen/entrypoint/sampleservice/stream/main.go:31 +0xc8
```

**Comment by mattmoor** [comment]
Using a `sync.WaitGroup` that closes `errCh` after `wg.Wait()` in a fourth go routine seems to work, but I think this logic should be reworked to consider semi-streamed methods too (this is just the most complicated).
